### ISSUE TITLE
Pull part 1 and part 2 headers into their own part-1.xhtml and part-2.xhtml files

### ISSUE THREAD

**Issue by acabal** [drgrigg/arthur-conan-doyle_a-study-in-scarlet#1]

**Comment by acabal** [comment]
Also, I don't think those are bridgeheads but subtitles; please remove the trailing periods in that case

**Comment by drgrigg** [comment]
OK. I wasn't sure about the need for separate files for part headers. I don't think it's covered in the typography manual (but I could be wrong!). I've converted the bridgeheads into subtitles and updated the ToC accordingly. However, for the first part I've removed the parentheses around the subtitle as it just looked odd in the page title and ToC. I don't know that they add anything, anyway. Also updated the manifest and spine in content.opf.

**Comment by acabal** [comment]
It's not in there yet, but explicit standards for filesystem layout are in the new single manual I'm working on.  (It's basically just what we've already been doing.)

**Comment by drgrigg** [comment]
Is there/will there be a repository for the manuals/web pages?

**Comment by acabal** [comment]
Maybe someday, but they're just the raw HTML pages you already see. I'm still working on them though and they're in a sloppy state.
